### ISSUE TITLE
Update Nokogiri transform XSL

### ISSUE THREAD

**Issue by Novtopro** [metanorma/xml-c14n#4]
When I was working on https://github.com/metanorma/niso-jats/issues/18, I found that I needed to sort the nodes properly on the same level to make sure all the specs could pass. 

In order to do that, I'll need to update the XML transform XSL.

**Comment by ronaldtse** [comment]
> sort the nodes properly on the same level

@Novtopro XML child element order can be sensitive for the parent element. It depends on whether the parent element needs to retain the order. 

Both are common patterns

Order sensitive:
```xml
<my-element>
  <data>foo</data>
  <note>Note on "foo"</note>
  <data>bar</data>
  <note>Note on "bar"</note>
</my-element>
```

(potentially) Order insensitive:
```xml
<my-element>
  <data>
    <text>foo</text>
    <note>Note on "foo"</note>
  </data>
  <data>
    <text>bar</text>
    <note>Note on "bar"</note>
  </data>
</my-element>
```

This demonstrates that element order cannot be

**Comment by Novtopro** [comment]
@opoudjis Yeah, I agree. We should provide an option to control it.

**Comment by Novtopro** [comment]
@opoudjis @ronaldtse I've updated the PR, could you please review again?

**Comment by ronaldtse** [comment]
@Novtopro I don't understand why we need to sort the elements at all? We should retain the order of elements.

Whether an XML element's children elements is order-sensitive is only known to whoever defined that XML schema, i.e. in the definition of the class that inherits from Lutaml::Model::Serializable?

**Comment by Novtopro** [comment]
Maybe I was misled by the existing spec. Originally we wrote the spec like

```ruby
  it "round-trips with xml-c14" do
    input = fixture.read

    serialized = described_class.from_xml(input)
    output = serialized.to_xml(
      pretty: true,
      declaration: true,
      encoding: "utf-8",
    )

    expect(output).to be_analogous_with(input)
  end
```

and I got errors like

![CleanShot 2024-11-01 at 14 11 08@2x](https://github.com/user-attachments/assets/33d37121-eb2f-4093-8265-b602c443a279)

The generated output is the same as the input except the order of the node is different. I noticed this issue and I thought that maybe we needed to update the transform XSL to sort the nodes on the same level if needed to make the comparison of XML pass like

```ruby
it "round-trips with xml-c14" do
    input = Xml::C14n.format(fixture.read)

    serialized = described_class.from_xml(input)
    output = Xml::C14n.format(serialized.to_xml)

    expect(output).to be_analogous_with(input)
end
```

But now, I realize that the failure may come from the missing `mixed` option and we should not transform the XML at all.

**Comment by Novtopro** [comment]
Okay, the failure does come from the missing `mixed` option and I'll leave the XSL untouched.
